#!/usr/bin/env node
/**
 * scripts/setup.js — ONE-TIME infrastructure setup.
 *
 * Run ONCE per environment before deploy.js:
 *   node scripts/setup.js [--env prod|staging]
 *
 * What it does:
 *   1. Creates 4 KV namespaces (gateway, auth, exam-engine, admin)
 *   2. Creates the R2 bucket
 *   3. Patches all wrangler.toml files with real KV IDs
 *   4. Stores JWT_SECRET in Cloudflare Worker secrets
 *   5. Stores RDS_PASSWORD + JWT_SECRET in AWS SSM Parameter Store
 *   6. Generates samconfig.toml from .env
 */

import { execSync, spawnSync } from "child_process";
import fs   from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT      = path.resolve(__dirname, "..");

// ── Load .env ──────────────────────────────────────────────────────────────────

function loadEnv() {
  const envPath = path.join(ROOT, ".env");
  if (!fs.existsSync(envPath)) {
    console.error("ERROR: .env not found. Copy .env.example and fill in values.");
    process.exit(1);
  }
  for (const line of fs.readFileSync(envPath, "utf8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const [key, ...rest] = trimmed.split("=");
    if (key && rest.length) process.env[key.trim()] = rest.join("=").trim();
  }
}

function need(key) {
  if (!process.env[key]) { console.error(`ERROR: ${key} is required in .env`); process.exit(1); }
  return process.env[key];
}

// ── Helpers ────────────────────────────────────────────────────────────────────

function run(cmd, opts = {}) {
  console.log(`  $ ${cmd}`);
  return execSync(cmd, { stdio: opts.quiet ? "pipe" : "inherit", encoding: "utf8", ...opts });
}

function runCapture(cmd) {
  return execSync(cmd, { stdio: "pipe", encoding: "utf8" });
}

// ── Step 1: Create KV namespaces ───────────────────────────────────────────────

function createKvNamespace(binding, title) {
  console.log(`\n  Creating KV: ${title}`);
  const out = runCapture(`wrangler kv namespace create "${title}" 2>&1`);
  const match = out.match(/id\s*=\s*"([a-f0-9]+)"/);
  if (!match) {
    // May already exist — try to list
    const list = runCapture(`wrangler kv namespace list 2>&1`);
    const ns = JSON.parse(list.match(/\[[\s\S]*\]/)?.[0] || "[]");
    const existing = ns.find(n => n.title === title);
    if (existing) { console.log(`  Already exists: ${existing.id}`); return existing.id; }
    console.error(`  ERROR: Could not create or find namespace "${title}"`);
    console.error(out);
    process.exit(1);
  }
  console.log(`  Created: ${match[1]}`);
  return match[1];
}

// ── Step 2: Patch wrangler.toml ────────────────────────────────────────────────

function patchToml(tomlPath, placeholderKey, realId) {
  let content = fs.readFileSync(tomlPath, "utf8");
  content = content.replace(`id = "${placeholderKey}"`, `id = "${realId}"`);
  // Also patch preview_id (use same namespace for preview in dev — acceptable for v1)
  content = content.replace(/preview_id = "REPLACE_WITH[^"]*"/, `preview_id = "${realId}"`);
  fs.writeFileSync(tomlPath, content);
  console.log(`  Patched: ${path.relative(ROOT, tomlPath)}`);
}

// ── Step 3: Create R2 bucket ───────────────────────────────────────────────────

function createR2Bucket(name) {
  console.log(`\n  Creating R2 bucket: ${name}`);
  try {
    run(`wrangler r2 bucket create "${name}"`, { quiet: true });
    console.log("  Created.");
  } catch {
    console.log("  Already exists (ok).");
  }
}

// ── Step 4: Set Wrangler secrets ───────────────────────────────────────────────

function setWranglerSecret(workerName, secretName, value) {
  console.log(`  Setting secret ${secretName} on ${workerName}`);
  const proc = spawnSync("wrangler", ["secret", "put", secretName, "--name", workerName], {
    input: value,
    encoding: "utf8",
    stdio: ["pipe", "inherit", "inherit"],
  });
  if (proc.status !== 0) { console.error(`  ERROR setting secret`); process.exit(1); }
}

// ── Step 5: SSM parameters ────────────────────────────────────────────────────

function putSsm(name, value, type = "SecureString") {
  console.log(`  SSM: ${name}`);
  run(`aws ssm put-parameter --name "${name}" --value "${value}" --type "${type}" --overwrite`, { quiet: true });
}

// ── Step 6: Generate samconfig.toml ───────────────────────────────────────────

function genSamConfig() {
  const dest = path.join(ROOT, "platform/lambda/samconfig.toml");
  const content = `# Auto-generated by scripts/setup.js — DO NOT commit
[default.deploy.parameters]
stack_name   = "${process.env.SAM_STACK || "mock-test-platform"}"
region       = "${process.env.SAM_REGION || "ap-south-1"}"
capabilities = "CAPABILITY_IAM"
resolve_s3   = true
parameter_overrides = """
  RdsHost=${process.env.RDS_HOST || "FILL_IN_AFTER_FIRST_DEPLOY"}
  RdsPort=${process.env.RDS_PORT || "5432"}
  RdsDb=${process.env.RDS_DB || "mocktest"}
  RdsUser=${process.env.RDS_USER || "app"}
  RdsPassword={{resolve:ssm-secure:/mtp/prod/rds_password}}
  JwtSecret={{resolve:ssm-secure:/mtp/prod/jwt_secret}}
  R2Bucket=${process.env.R2_BUCKET || "mtp-exam-data"}
"""
`;
  fs.writeFileSync(dest, content);
  console.log(`  Generated: platform/lambda/samconfig.toml`);
}

// ── Main ──────────────────────────────────────────────────────────────────────

loadEnv();
const JWT_SECRET  = need("JWT_SECRET");
const R2_BUCKET   = process.env.R2_BUCKET || "mtp-exam-data";

console.log("\n══════════════════════════════════════");
console.log("  Mock Test Platform — Infrastructure Setup");
console.log("══════════════════════════════════════\n");

// 1. KV namespaces
console.log("▶ Step 1/6: Create KV namespaces");
const gatewayKvId     = createKvNamespace("KV", "mtp-gateway-kv");
const authKvId        = createKvNamespace("KV", "mtp-auth-kv");
const examKvId        = createKvNamespace("KV", "mtp-exam-kv");
const adminKvId       = createKvNamespace("KV", "mtp-admin-kv");

// 2. Patch wrangler.toml files
console.log("\n▶ Step 2/6: Patch wrangler.toml files");
patchToml(path.join(ROOT, "platform/gateway/wrangler.toml"),      "REPLACE_WITH_KV_ID",          gatewayKvId);
patchToml(path.join(ROOT, "modules/auth/wrangler.toml"),           "REPLACE_WITH_KV_ID",          authKvId);
patchToml(path.join(ROOT, "modules/exam-engine/backend/wrangler.toml"), "REPLACE_WITH_EXAM_KV_ID", examKvId);
patchToml(path.join(ROOT, "modules/admin/backend/wrangler.toml"),  "REPLACE_WITH_ADMIN_KV_ID",    adminKvId);

// 3. R2 bucket
console.log("\n▶ Step 3/6: Create R2 bucket");
createR2Bucket(R2_BUCKET);

// 4. Wrangler secrets (JWT_SECRET on each worker)
console.log("\n▶ Step 4/6: Set Wrangler secrets");
for (const worker of ["mtp-auth", "mtp-exam-engine", "mtp-admin"]) {
  setWranglerSecret(worker, "JWT_SECRET", JWT_SECRET);
}

// 5. AWS SSM params
console.log("\n▶ Step 5/6: Store secrets in AWS SSM");
putSsm("/mtp/prod/jwt_secret",    JWT_SECRET);
putSsm("/mtp/prod/rds_password",  need("RDS_PASSWORD"));

// 6. samconfig.toml
console.log("\n▶ Step 6/6: Generate samconfig.toml");
genSamConfig();

console.log("\n✅  Setup complete.");
console.log("   Next: node scripts/deploy.js\n");
